# Generated by Django 3.2.7 on 2022-06-09 20:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20220609_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Lead', 'Project Lead'), ('Tech', 'Technical Member'), ('Support', 'Support Member')], default='Support', max_length=20, verbose_name='Project Role'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.TextField(default='say something about your role', verbose_name='About me'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('edbdd199-bb28-458c-940c-e18906d7b00f'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_buyer',
            field=models.BooleanField(default=False, help_text='Buy licenses?', verbose_name='Buyer'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_seller',
            field=models.BooleanField(default=False, help_text='Owner of the license?', verbose_name='Seller'),
        ),
    ]
