# Generated by Django 3.2.7 on 2022-06-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_buyer',
            field=models.BooleanField(default=False, help_text='Buy a licenses?', verbose_name='Buyer'),
        ),
    ]
