# Generated by Django 3.2.7 on 2022-06-09 20:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20220609_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7c811bd2-f0b9-42c9-9afa-8f5a96f068ff'), editable=False, unique=True),
        ),
    ]
