# Generated by Django 3.2.7 on 2022-06-10 02:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('95b9184b-0878-4a96-9358-2eaa56e3e0e9'), editable=False, unique=True),
        ),
    ]
