# Generated by Django 3.2.7 on 2022-06-10 02:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b898d433-8756-4801-b176-df8704ba40b2'), editable=False, unique=True),
        ),
    ]
