# Generated by Django 3.2.7 on 2022-06-10 02:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d62b529c-2454-41c1-9853-abc8de908f3c'), editable=False, unique=True),
        ),
    ]
