# Generated by Django 3.2.7 on 2022-06-10 02:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4c39a764-d442-4cc0-b5ed-711a37e9f329'), editable=False, unique=True),
        ),
    ]
