# Generated by Django 3.2.7 on 2022-06-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='property',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.15, help_text='5% property tax charged', max_digits=8, verbose_name='Property Tax'),
        ),
    ]
