# Generated by Django 3.2.7 on 2022-06-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20220620_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=4, verbose_name='Bathrooms'),
        ),
    ]
