#!/bin/bash

set -o errexit

set -o nounset


worker_ready(){
    celery -A drf_gis inspect ping
}

until worker_ready; do
    >&2 echo 'Celery workers not available :-('
    sleep 1
    
done
>&2 echo 'Celery workers are available and ready!...:-)'

flower \
--app=drf_gis \
--broker="${CELERY_BROKER}"